name: "Create New Release"

on:
  workflow_call:
    inputs:
      godot_version:
        required: false
        type: string
        default: 4.2.2

jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.2.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup
        run: |
          echo "VERSION="$(echo ${{ github.head_ref }} | grep -o [0-9.] | tr -d '\n') >> $GITHUB_ENV
          echo "RELEASE_TYPE="$(echo ${{ github.head_ref }} | cut -c 15-) >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}-${{ env.RELEASE_TYPE }}
          release_name: v${{ env.VERSION }}-${{ env.RELEASE_TYPE }}
          draft: false
          prerelease: false