name: "Export Release"
on:
  release:
    types: [published]

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: BitBuster

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
    
      - name: Authorize GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      # Step to Authenticate with GCP
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/$GODOT_VERSION.stable.mono ~/.local/share/godot/export_templates/$GODOT_VERSION.stable.mono
          echo "VERSION=$(grep -o 'config/version="[^"]*"' project.godot | tr -d "config/version=\"")" >> $GITHUB_ENV
          echo "RELEASE_TYPE="$(echo ${{ github.event.release.name }} | grep -o '[^v0-9\.\-]' | tr -d '\n') >> $GITHUB_ENV

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe

      - name: Upload to GCS
        run: |
          (cd build/windows; zip -r ../../$EXPORT_NAME-$VERSION.zip ./)
          gsutil cp ./windows-$VERSION.zip gs://${{ secrets.GCP_BITBUCKET_RELEASE_BUCKET }}/$RELEASE_TYPE/windows 

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Authorize GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
  
      # Step to Authenticate with GCP
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          echo "VERSION=$(grep -o 'config/version="[^"]*"' project.godot | tr -d "config/version=\"")" >> $GITHUB_ENV
          echo "RELEASE_TYPE="$(echo ${{ github.event.release.name }} | grep -o '[^v0-9\.\-]' | tr -d '\n') >> $GITHUB_ENV


      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64

      - name: Upload to GCS
        run: |
          (cd build/linux; zip -r ../../$EXPORT_NAME-$VERSION.zip ./)
          gsutil cp ./linux-$VERSION.zip gs://${{ secrets.GCP_BITBUCKET_RELEASE_BUCKET }}/$RELEASE_TYPE/linux
      