name: "Bump Version"

on:
  workflow_call:
    inputs:
      godot_version:
        required: false
        type: string
        default: 4.2.2

jobs:
  increment-release:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.2.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change Version to Branch Name
        run: |
          echo "NEW_VERSION="$(echo ${{ github.head_ref }} | cut -c 15-) >> $GITHUB_ENV
          sed -i 's/config\/version=0.0.1/config\/version=${{ env.NEW_VERSION }}/' project.godot

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit-message: "Automated Version Bump"
          file_pattern: '*.godot'

