name: "Release Executable"

on:
  pull_request:
    branches:
      - main
    types:
      - closed      

jobs:
  export:
    if: ${{ github.event.pull_request.merged == true }}
    name: Export Windows and Linux
    uses: ./.github/workflows/export.yml 
    secrets: inherit
    with: 
      export_name: Bitbuster

  increment-version:
    name: Bump Version
    uses: ./.github/workflows/increment-version.yml
    needs: [export]
    secrets: inherit

  make-release:
    name: Make New Release
    uses: ./.github/workflows/create-release.yml 
    needs: [increment-version]
    secrets: inherit
